### ISSUE TITLE
22- función genrnd que retorna una lista con 500.000.000.000.000.000 números aleatorios.

### ISSUE THREAD

**Issue by KC-2022** [ispc-programador2022/a4g2-a4g2#26]

**Comment by MarceloGustavoCordoba** [comment]
se limita la lista devuelta a 100.000.000 de numeros, mas alla de esa cantidad presenta error por ocupar toda la RAM. 

![image](https://user-images.githubusercontent.com/104207892/176087585-249475d7-7076-4d3b-8a52-9d192de35aaf.png)
